INSERT INTO Marcas (Nombre, Activo)
VALUES
('Coca-Cola', 1),
('Gamesa', 1),
('Ricolino', 1),
('Sabritas', 1),
('Pepsi', 1),
('Bimbo', 1),
('Marinela', 1),
('Barcel', 1),
('La Coste�a', 1),
('Herdez', 1),
('Verde Valle', 1),
('La Moderna', 1),
('Jumex', 1),
('Del Valle', 1),
('Lala', 1),
('Alpura', 1),
('Nutrileche', 1),
('Santa Clara', 1),
('Nestl�', 1),
('Nescaf�', 1),
('Nido', 1),
('La Lechera', 1),
('Maggi', 1),
('Carlos V', 1),
('KitKat', 1),
('Oreo', 1),
('Ritz', 1),
('Trident', 1),
('Halls', 1),
('Quaker', 1),
('Gatorade', 1),
('7UP', 1),
('Manzanita Sol', 1),
('Doritos', 1),
('Cheetos', 1),
('Tostitos', 1),
('Chokis', 1),
('Emperador', 1),
('Saladitas', 1),
('Maruchan', 1);